1

diff --git a/runit/squid/run b/runit/squid/run
--- a/runit/squid/run
+++ b/runit/squid/run
@@ -2,14 +2,18 @@
 
 exec 2>&1
 
-if [ -z "${SS_MODULE}" ]; then
-    SS_MODULE="ss-server"
-fi
+if [ "${SQUID_FLAG}" == "true" ]; then
+	if [ -z "${SS_MODULE}" ]; then
+		SS_MODULE="ss-server"
+	fi
 
-if [ "${SS_MODULE}"="ss-local" ]; then
-    echo "starting squid..."
-    exec chpst -u squid squid
+	if [ "${SS_MODULE}" == "ss-local" ]; then
+		echo "starting squid..."
+		exec chpst -u squid squid
+	else
+		echo "Error: SS_CONFIG is empty, exit!"
+		exit 1
+	fi
 else
-    echo "Error: SS_CONFIG is empty, exit!"
-    exit 1
+    exit 0
 fi
